### ISSUE TITLE
Sift gem dependency inconsistency

### ISSUE THREAD

**Issue by MauricioMurga** [SiftScience/sift-partner-ruby#6]
In gemspec it is specified:
s.add_dependency "sift", ">= 1.1.6.2"

Newer versions of the sift gem are incompatible with the sift-partner-ruby gem:
https://github.com/SiftScience/sift-ruby/blob/71178d5096c92199c71716688dd49cf85148da8b/lib/sift/client.rb#L23
https://github.com/SiftScience/sift-ruby/blob/master/lib/sift/client.rb#L24

**Comment by MauricioMurga** [comment]
Hi there, is this compatibility issue going to be resolved? It has been open for a long time.

Thanks,

**Comment by fredsadaghiani** [comment]
@yschatzberg can you take a look?

**Comment by yschatzberg** [comment]
Opened a PR which should Fix: https://github.com/SiftScience/sift-ruby/pull/28

**Comment by aaronTufts** [comment]
Closing as the change was merged. Please reopen if still an issue.
